"""Rebuild bibliography.bib from the paper's bib/ directory.

Run from web/. The paper's bib lives outside this repository, so pass its path
if the checkout does not sit beside it:

    python tools/build_bibliography.py ../../bib

Entries are copied verbatim except for four fields. The paper's bib mixes full
ACL Anthology entries (which carry editor, publisher, address and month) with
minimal ones that do not. BibTeX styles ignore the difference; the APA CSL used
on the web page does not, so the same kind of venue rendered two different ways
- some entries trailing "Association for Computational Linguistics." and a list
of editors, others not. Dropping those fields makes every proceedings entry
render the same way.
"""

import glob
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "../../bib"
OUT = "bibliography.bib"
DROP = ("editor", "publisher", "address", "month")

def strip_fields(entry: str) -> str:
    out, depth, skip = [], 0, False
    for line in entry.split("\n"):
        stripped = line.strip()
        if not skip and depth == 0:
            m = re.match(r"(\w+)\s*=", stripped)
            if m and m.group(1).lower() in DROP:
                skip = True
        if skip:
            depth += line.count("{") - line.count("}")
            # The field ends on the line whose braces close and which ends the value.
            if depth <= 0:
                skip, depth = False, 0
            continue
        out.append(line)
    text = "\n".join(out)
    # A dropped field can leave a trailing comma before the closing brace.
    return re.sub(r",(\s*\n\})", r"\1", text)

files = sorted(glob.glob(os.path.join(SRC, "*.bib")))
if not files:
    sys.exit(f"no .bib files under {SRC}")

chunks = [
    "% Generated by tools/build_bibliography.py from the paper's bib/.\n"
    "% Do not edit by hand. rehype-citation emits only the cited entries.\n"
]
total = 0
for f in files:
    with open(f, encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    entries = re.findall(r"@\w+\{.*?\n\}", text, re.S)
    total += len(entries)
    chunks.append(f"\n% ---- {os.path.basename(f)} ----\n")
    chunks.append("\n\n".join(strip_fields(e) for e in entries) + "\n")

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("".join(chunks))
print(f"wrote {OUT}: {total} entries from {len(files)} files, dropped {', '.join(DROP)}")
